### ISSUE TITLE
Получение печатных форм выписок банка

### ISSUE THREAD

**Issue by vasilevTechmoney** [Host-to-Host-Instructions/alfalink-1c-directbank-via-api#7]
Добрый день.
Не увидел методов по получению печатных форм выписок банка. Такого функционала не предусмотрено в API?

**Comment by artik008** [comment]
Добрый день!
На данный момент функционал печатных форм не реализован в модуле 1С:Директбанк
Печатные формы платежей реализованы в системе Host-to-host, печатные формы выписок появятся там же в этом году.
